# Generated by Django 4.1.7 on 2025-08-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
