# Generated by Django 4.1.7 on 2025-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='learning_items/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'موارد در حال یادگیری',
                'verbose_name_plural': 'موارد در حال یادگیری',
            },
        ),
    ]
